const OneProductData = [
  {
    _id: "000",
    productName: "WOMEN tsamts",
    additionInfo: "Daavuun materialaar hiigdsen",
    barCode: 12345678,
    productImage: ["/orderedProd.png", "/orderedProd.png", "/orderedProd.png"],
    mainPrice: 19000,
    quantity: 20,
    soldQty: 10,
    mainCategory: "Emegtei",
    secondCategory: "Tsamts",
    color: ["#CD5C5C", "#F08080", "#FFA07A"],
    size: ["xl", "l", "m", "s"],
    tag: ["emegtei", "tsamts"],
    createdAt: "2021/12/31",
    updatedAt: "2021/12/31",
  },
  {
    _id: "111",
    productName: "Men umd",
    additionInfo: "Nylon materialaar hiigdsen",
    barCode: 123456789,
    productImage: ["/orderedProd.png", "/jacket.png", "/orderedProd.png"],
    mainPrice: 19000,
    quantity: 20,
    soldQty: 3,
    mainCategory: "Eregtei",
    secondCategory: "Umd",
    color: ["#C0C0C0", "#000000", "#800000"],
    size: ["xl", "l", "m", "s"],
    tag: ["eregtei", "umd"],
    createdAt: "2021/12/31",
    updatedAt: "2021/12/31",
  },
  {
    _id: "222",
    productName: "Toddler gutal",
    additionInfo: "Daavuun materialaar hiigdsen",
    barCode: 103456789,
    productImage: ["/orderedProd.png", "/orderedProd.png", "/orderedProd.png"],
    mainPrice: 19000,
    quantity: 20,
    soldQty: 1,
    mainCategory: "Toddler",
    secondCategory: "Gutal",
    color: ["#00FFFF", "#008080", "#000080"],
    size: ["xl", "l", "m", "s"],
    tag: ["huuhed", "gutal"],
    createdAt: "2021/12/31",
    updatedAt: "2021/12/31",
  },
];

export default OneProductData;
